name: publish on pypi

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  pip install poetry && poetry install
            - name: Build
              run: |
	              poetry build
            - name: Publish to PyPi
              env:
                  PYPI_USERNAME: @token
                  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                  poetry build && poetry publish
